version: "3"
services: 
  db:
    image: mariadb:latest
    container_name: mariadb_local
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root1!"
      TZ: Asia/Seoul
    volumes:
      - /Users/choedeb/docker/mariadb/data:/var/lib/mysql
      - /Users/choedeb/docker/mariadb/config:/etc/mysql/conf.d